[package]
name = "gradflow"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
rand = "0.8"
rand_distr = "0.4"
plotters = "0.3"
statrs = "0.18.0"

[dev-dependencies]
mnist = "0.6.0"